# Generated by Django 5.2.16 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='member_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo of Member'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nid_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/nid/', verbose_name='Photo of NID'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nominee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/nominees/', verbose_name='Photo of Nominee'),
        ),
    ]
