# Generated by Django 5.2.16 on 2026-09-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberprofile_member_photo_memberprofile_nid_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Officer Approval'), ('ACTIVE', 'Active / Approved'), ('REJECTED', 'Application Rejected'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=15),
        ),
    ]
