# Generated by Django 5.2.16 on 2026-09-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('BANK', 'Bank Transfer'), ('SSLCOMMERZ', 'SSLCOMMERZ Gateway'), ('SAVINGS', 'Savings Account Balance')], default='CASH', max_length=20),
        ),
        migrations.CreateModel(
            name='SSLPaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=64, unique=True)),
                ('val_id', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('VALID', 'Payment Validated / Success'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Payment Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_sessions', to='savings.savingsaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
