# Generated by Django 5.2.16 on 2026-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallment',
            name='payment_method',
            field=models.CharField(choices=[('SAVINGS', 'Savings Account Balance'), ('CASH', 'Cash Payment'), ('BKASH', 'bKash Mobile Banking'), ('NAGAD', 'Nagad Mobile Banking'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='loaninstallment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
